version: "3.2"
services:
  bg-host:
    restart: unless-stopped
    container_name: sht-bg-host
    build:
      context: ./../../src
      dockerfile: ./../tools/deploy/bg-host.Dockerfile
    env_file:
      - bg-host.env
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    #   - Serilog__WriteTo__FileLogger__Args__path=${Serilog__WriteTo__FileLogger__Args__path}
    #   - DataAccessOptions__ConnectionsOptions__DefaultConnection=${DataAccessOptions__ConnectionsOptions__DefaultConnection}
    #   - ApplicationUri=${ApplicationUri}
    #   - ExecutionContextOptions__DefaultSystemUserEmail=${ExecutionContextOptions__DefaultSystemUserEmail}
    volumes:
      - sht-bg-host-logs:/app/Logs
    networks:
      - database
networks:
  database:
volumes:
  sht-bg-host-logs:
  