version: "3.2"
services:
  db:
    image: "postgres"
    container_name: "db"
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5433:5432"
    volumes:
      - sht-db-data:/var/lib/postgresql/data
    networks:
      - database
  db-update:
    command: update
    build:
      context: ./../../src
      dockerfile: ./../tools/deploy/db.migrations.Dockerfile
    env_file:
      - db.env
    networks:
      - database
networks:
  database:
volumes:
  sht-db-data: